/*
 * workout storage
 * to be replaced by db service
*/
const _ = require('lodash');
const moment = require('moment');

module.exports = {
  amanda: {
    name: 'Amanda',
    description: '9, 7 and 5 reps of muscle-ups and snatches (135/95lbs)',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['muscle-up','snatch'],
    repScheme: [9,7,5],
    weights: {snatch: '135/95'},
    linksToMovement: ['http://wodwell.com/wod/amanda/'],
    categories: ['gymanastics','olympic-lifting','barbell','rings','couplet'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension']
  },
  angie: {
    name: 'Angie',
    description: '100 pull-ups, 100 push-ups, 100 sit-ups, 100 air squats',
    timeScheme: 'For Time',
    averageTime: '30 minutes',
    movements: ['pull-up','push-up','sit-ups','air-squats'],
    repScheme: [100,100,100,100],
    weights: {},
    linksToMovement: ['http://wodwell.com/wod/angie/'],
    categories: ['gymanastics','pull-up'],
    warmUps: [],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  barbara: {
    name: 'Barbara',
    description: '5 rounds for time 20 pull-ups, 30 push-ups, 40 sit-ups, 50 air-squats, 3 minutes rest',
    timeScheme: 'For Time',
    averageTime: '30 minutes',
    movements: ['pull-up','push-up','sit-ups','air-squats'],
    repScheme: [20,30,40,50],
    weights: {},
    linksToMovement: ['http://wodwell.com/wod/barbara/'],
    categories: ['gymanastics','pull-up','push-ups','sit-ups','air-squats'],
    warmUps: [],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  chelsea: {
    name: 'Chelsea',
    description: '5 pull-ups, 10 push-ups, 15 air-squats',
    timeScheme: 'EMOM',
    averageTime: '20 minutes',
    movements: ['pull-ups','push-ups','air-squats'],
    repScheme: [5,10,15],
    weights: {},
    linksToMovement: ['http://wodwell.com/wod/chelsea/'],
    categories: ['pull-ups', 'push-ups', 'air-squats'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  cindy: {
    name: 'Cindy',
    description: '20 minutes of 5 pull-ups, 10 push-ups, 15 air-squats',
    timeScheme: 'AMRAP',
    averageTime: '20 minutes',
    movements: ['pull-ups','push-ups','air-squats'],
    repScheme: [5,10,15],
    weights: {},
    linksToMovement: ['http://wodwell.com/wod/cindy/'],
    categories: ['gymnastics','bodyweight','pull-ups','push-ups','air-squats'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  diane: {
    name: 'Diane',
    description: '21 deadlifts, 21 handstand push-ups, 15 deadlifts, 15 handstand push-ups, 9 deadlifts, 9 handstand push-ups',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['deadlifts','handstand push-ups'],
    repScheme: [21,15,9],
    weights: { deadlift: 225 },
    linksToMovement: ['http://wodwell.com/wod/diane/'],
    categories: ['deadlifts','handstand push-ups'],
    warmUps: ['KB deadlifts','kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  elizabeth: {
    name: 'Elizabeth',
    description: '21 squat cleans, 21 ring-dips, 15 squat cleans, 15 ring-dips, 9 squat cleans, 9 ring-dips',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['squat cleans','ring-dips'],
    repScheme: [21,15,9],
    weights: { 'squat-cleans': '135/95' },
    linksToMovement: ['http://wodwell.com/wod/elizabeth/'],
    categories: ['squat cleans','ring-dips'],
    warmUps: ['KB deadlifts','kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  eva: {
    name: 'Eva',
    description: '5 rounda Run 800 meters, 30 Kettlebell swings, 30 pullups',
    timeScheme: 'For Time',
    averageTime: '10 minutes',
    movements: ['run','kettlebell-swing','pull-up'],
    repScheme: [800,30,30],
    weights: {'kettlebell': '70/53'},
    linksToMovement: ['http://wodwell.com/wod/eva/'],
    categories: ['run','kettlebell-swing','pull-up'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  fran: {
    name: 'Fran',
    description: '21 thrusters, 21 pull-ups, 15 thrusters, 15 pull-ups, 9 thrusters, 9 pull-ups',
    timeScheme: 'For Time',
    averageTime: '3 minutes',
    movements: ['pull-up','thruster'],
    repScheme: [21,15,9],
    weights: {thruster: '95/65'},
    linksToMovement: ['http://wodwell.com/wod/fran/'],
    categories: ['gymanastics','pull-up'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  grace: {
    name: 'Grace',
    description: '30 ground-to-overheads clean and jerk',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['ground-to-overhead','clean','jerk'],
    repScheme: [30],
    weights: {'clean-and-jerk': '135/95'},
    linksToMovement: ['http://wodwell.com/wod/grace/'],
    categories: ['barbell', 'clean-and-jerk'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  gwen: {
    name: 'Gwen',
    description: '15-12-9 clean and jerk',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['ground-to-overhead','clean-jerk'],
    repScheme: [15,12,9],
    weights: {},
    linksToMovement: ['http://wodwell.com/wod/gwen/'],
    categories: ['barbell', 'clean-and-jerk'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  helen: {
    name: 'Helen',
    description: '3 rounds 400m run, 21 kettlebell swings, 12 pull-ups',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['run','kettlebell-swing','pull-up'],
    repScheme: [400,21,12],
    weights: {'kettlebell': '53/35'},
    linksToMovement: ['http://wodwell.com/wod/helen/'],
    categories: ['run','kettlebell-swing','pull-up'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  isabel: {
    description: '30 ground-to-overheads snatch',
    timeScheme: 'For Time',
    averageTime: '5 minutes',
    movements: ['ground-to-overhead','snatch'],
    repScheme: [30],
    weights: {snatch: '135/95'},
    linksToMovement: ['http://wodwell.com/wod/isabel/'],
    categories: ['barbell','snatch','power-snatch'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  jackie: {
    name: 'Jackie',
    description: '1000m row, 50 thrusters, 30 pull-ups',
    timeScheme: 'For Time',
    averageTime: '12 minutes',
    movements: ['row','thrusters','pull-ups'],
    repScheme: [1000,50,30],
    weights: {thruster: '45'},
    linksToMovement: ['http://wodwell.com/wod/jackie/'],
    categories: ['barbell','snatch'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  karen: {
    name: 'Karen',
    description: '150 wallballs',
    timeScheme: 'For Time',
    averageTime: '10 minutes',
    movements: ['wallball'],
    repScheme: [20],
    weights: {thruster: '45'},
    linksToMovement: ['http://wodwell.com/wod/jackie/'],
    categories: ['wallball'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  kelly: {
    name: 'Kelly',
    description: '5 rounds Run 400 meters, 30 box jump, 24 inch box, 30 Wall ball shots, 20 pound ball',
    timeScheme: 'For Time',
    averageTime: '12 minutes',
    movements: ['run','box-jump','wallballs'],
    repScheme: [400,30,30],
    weights: {'wallball': '20/14'},
    linksToMovement: ['http://wodwell.com/wod/kelly/'],
    categories: ['run','box-jump','wallballs'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  linda: {
    name: 'Linda',
    description: '10,9,8,7,6,5,4,3,2,1 reps of Deadlift 1.5 BW, Bench BW, Clean 3/4 BW',
    timeScheme: 'For Time',
    averageTime: '10 minutes',
    movements: ['deadlift','bench','clean'],
    repScheme: [10,9,8,7,6,5,4,3,2,1],
    weights: {deadlift: 'bodyweight',bench: 'bodyweight', clean: 'bodyweight'},
    linksToMovement: ['http://wodwell.com/wod/linda/'],
    categories: ['barbell','deadlift','bench','clean','3-bars-of-death'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  lynne: {
    name: 'Lynne',
    description: '5 rounds for max reps, Bench press BW, pull-ups',
    timeScheme: 'For Time',
    averageTime: '10 minutes',
    movements: ['bench','pull-ups'],
    repScheme: ['max reps'],
    weights: {bench: 'bodyweight'},
    linksToMovement: ['http://wodwell.com/wod/lynne/'],
    categories: ['bench','pull-ups'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  mary: {
    name: 'Mary',
    description: '5 Handstand push-ups, 10 1-legged squats, 15 Pull-ups',
    timeScheme: 'AMRAP',
    averageTime: '20 minutes',
    movements: ['push-ups','pistol-squat','pull-up'],
    repScheme: [5,10,15],
    weights: {},
    linksToMovement: ['http://wodwell.com/wod/mary/'],
    categories: ['push-ups','pistol-squat','pull-up'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  nancy: {
    name: 'Nancy',
    description: '400 meter run, Overhead squat',
    timeScheme: 'For Time',
    averageTime: '8 minutes',
    movements: ['run','OHS'],
    repScheme: [400,15],
    weights: {ohs: '95/65'},
    linksToMovement: ['http://wodwell.com/wod/nancy/'],
    categories: ['run','overhead-squat'],
    warmUps: ['kitchen-sink-stretch','shoulder-pass-throughs','air-squat','banded-OH-extension'],
    date: moment().format('YYYY-MM-DD_HH:MM:ss_dddd')
  },
  // workoutName: {
  //   name: '',
  //   description: '',
  //   timeScheme: '',
  //   averageTime: '',
  //   movements: [],
  //   repScheme: [],
  //   weights: {},
  //   linksToMovement: [],
  //   categories: [],
  //   warmUps: [],
  //   date: //moment().format('YYYY-MM-DD_HH-MM_dddd')
  // }
};
